export interface Stay {
  id: number;
  title: string;
  description: string;
  price: string;
  image: string;
  rating: number;
  location: string;
  type: 'Hotels' | 'Hostels' | 'Homestays' | 'CoLiving' | 'Resorts';
  distance?: string;
  trending?: boolean;
  amenities: string[];
}

export const stays: Stay[] = [
  {
    id: 1,
    title: 'The Leela Palace Bengaluru',
    description: 'Experience unparalleled luxury in the garden city with spacious rooms featuring private balconies overlooking lush gardens',
    price: '₹12,000/night',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    rating: 4.9,
    location: 'Old Airport Road, Bengaluru',
    type: 'Hotels',
    trending: true,
    amenities: ['Multiple Restaurants', 'Spa', 'Fitness Center', 'Outdoor Pool', 'Private Balcony', 'Lush Gardens'],
  },
  {
    id: 2,
    title: 'The Ritz-Carlton, Bangalore',
    description: 'Elegant luxury in the heart of Bangalore with stunning city views and world-class amenities',
    price: '₹15,000/night',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    location: 'Residency Road, Bengaluru',
    type: 'Hotels',
    trending: true,
    amenities: ['Rooftop Bar', 'Multiple Restaurants', 'Spa', 'Fitness Center', 'Outdoor Pool', 'City Views'],
  },
  {
    id: 3,
    title: 'JW Marriott Hotel Bengaluru',
    description: 'Luxurious accommodation with panoramic city views and exceptional dining experiences',
    price: '₹10,000/night',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    location: 'Vittal Mallya Road, Bengaluru',
    type: 'Hotels',
    trending: true,
    amenities: ['Multiple Restaurants', 'Spa', 'Fitness Center', 'Outdoor Pool', 'City Views', 'Business Center'],
  },
  {
    id: 4,
    title: 'The Oberoi, Bengaluru',
    description: 'Luxury oasis in the city center with private balconies overlooking landscaped gardens',
    price: '₹14,000/night',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    location: 'Mahatma Gandhi Road, Bengaluru',
    type: 'Hotels',
    amenities: ['Private Balcony', 'Multiple Restaurants', 'Spa', 'Fitness Center', 'Outdoor Pool', 'Garden Views'],
  },
  {
    id: 5,
    title: 'Shangri-La Hotel, Bengaluru',
    description: 'Contemporary luxury with panoramic city views and exceptional dining options',
    price: '₹12,000/night',
    image: 'https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    location: 'Palace Road, Vasanth Nagar, Bengaluru',
    type: 'Hotels',
    amenities: ['Rooftop Lounge', 'Multiple Restaurants', 'Spa', 'Fitness Center', 'Outdoor Pool', 'City Views'],
  },
  {
    id: 6,
    title: 'ibis Bengaluru Outer Ring Road',
    description: 'Modern comfort with essential amenities for business and leisure travelers',
    price: '₹3,500/night',
    image: 'https://images.unsplash.com/photo-1587985064135-0366536eab42?auto=format&fit=crop&w=800&q=80',
    rating: 4.2,
    location: 'Marathahalli - Sarjapur Outer Ring Road, Bengaluru',
    type: 'Hotels',
    distance: '2.5 km',
    amenities: ['Free WiFi', '24/7 Fitness Center', 'Restaurant', 'Business Center', 'Meeting Rooms'],
  },
  {
    id: 7,
    title: 'Treebo Trend Edge',
    description: 'Affordable comfort in prime location with essential amenities',
    price: '₹2,500/night',
    image: 'https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80',
    rating: 4.0,
    location: 'Off Brigade Road, Bengaluru',
    type: 'Hotels',
    distance: '1.0 km',
    amenities: ['Free WiFi', 'Complimentary Breakfast', 'Air Conditioning', '24/7 Reception', 'Room Service'],
  },
  {
    id: 8,
    title: 'IBIS Bengaluru City Centre',
    description: 'Contemporary budget hotel with modern amenities in central location',
    price: '₹3,000/night',
    image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=800&q=80',
    rating: 4.1,
    location: 'Richmond Road, Bengaluru',
    type: 'Hotels',
    distance: '0.8 km',
    amenities: ['Free WiFi', 'Fitness Center', 'Restaurant', 'Meeting Rooms', 'City Views'],
  },
  {
    id: 9,
    title: 'OYO Premium Koramangala',
    description: 'Budget-friendly accommodation with essential amenities',
    price: '₹1,000/night',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    rating: 3.8,
    location: 'Koramangala, Bengaluru',
    type: 'Hotels',
    distance: '3.2 km',
    amenities: ['Free WiFi', 'Air Conditioning', 'Complimentary Breakfast', '24/7 Reception'],
  },
  {
    id: 10,
    title: 'FabHotel Corporate Crown',
    description: 'Business-friendly budget hotel with comfortable amenities',
    price: '₹2,000/night',
    image: 'https://images.unsplash.com/photo-1584132967334-10e028bd69f7?auto=format&fit=crop&w=800&q=80',
    rating: 4.0,
    location: 'Koramangala, Bengaluru',
    type: 'Hotels',
    distance: '2.8 km',
    amenities: ['Free WiFi', 'Complimentary Breakfast', 'Business Center', 'Room Service', '24/7 Reception'],
  },
  {
    id: 11,
    title: 'COVIE Bannerghatta 185',
    description: 'Premium co-living space with modern amenities and vibrant community living experience',
    price: '₹15,700/month',
    image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    location: 'Bannerghatta, Bangalore',
    type: 'CoLiving',
    trending: true,
    amenities: ['Fully Furnished Rooms', 'Housekeeping Services', 'High-speed Internet', 'Communal Lounges', 'Co-working Areas'],
  },
  {
    id: 12,
    title: 'Keys On Rent Garnet House',
    description: 'Luxury co-living space with premium amenities and proximity to business hubs',
    price: '₹30,000/month',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    location: 'Mahadevpura, Bangalore',
    type: 'CoLiving',
    trending: true,
    amenities: ['Modern Furnishings', 'Housekeeping', 'WiFi', 'Communal Spaces', 'Business Hub Proximity'],
  },
  {
    id: 13,
    title: 'Skep Coliving',
    description: 'Comfortable living spaces with top-notch security and community events',
    price: 'Contact for pricing',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    location: 'Prime areas across Bangalore',
    type: 'CoLiving',
    amenities: ['Comfortable Living Spaces', 'Top-notch Security', 'Community Events', 'Easy Access to Amenities'],
  },
  {
    id: 14,
    title: 'Colive',
    description: 'Modern co-living spaces with premium amenities and vibrant community engagement',
    price: 'Contact for pricing',
    image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    location: 'Koramangala, HSR Layout, Whitefield',
    type: 'CoLiving',
    amenities: ['Fully Furnished Rooms', 'High-speed Internet', '24/7 Security', 'Regular Housekeeping', 'Community Engagement'],
  },
  {
    id: 15,
    title: 'Zolo Stays',
    description: 'Affordable co-living spaces with essential amenities and community events',
    price: '₹5,000/month (triple sharing)',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    location: 'Koramangala, HSR Layout, Electronic City',
    type: 'CoLiving',
    amenities: ['Fully Furnished Rooms', 'WiFi', 'Daily Housekeeping', 'Community Events', 'Multiple Sharing Options'],
  },
  {
    id: 16,
    title: 'Alexandro Coliving',
    description: 'Flexible co-living spaces with various sharing options and modern amenities',
    price: '₹11,000/month (single)',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    location: 'Various locations across Bangalore',
    type: 'CoLiving',
    amenities: ['Fully Furnished Rooms', 'WiFi', 'Housekeeping', 'Communal Areas', 'Multiple Sharing Options'],
  },
  {
    id: 17,
    title: 'Housr',
    description: 'Premium serviced rooms designed for long-term stays with modern appliances and elegant decor',
    price: 'Contact for pricing',
    image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    location: 'Indiranagar, Bangalore',
    type: 'CoLiving',
    trending: true,
    amenities: ['Modern Appliances', 'Elegant Decor', 'High-speed WiFi', 'Business Hub Proximity', 'Entertainment Spots Nearby'],
  },
  {
    id: 18,
    title: 'Club Sycamore Tree by Hyphen',
    description: 'Luxury co-living space with high-quality finishes and premium amenities',
    price: '₹40,000/month (12-month contract)',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.8,
    location: 'Central Bangalore',
    type: 'CoLiving',
    trending: true,
    amenities: ['Luxurious Living Spaces', 'High-quality Finishes', 'Communal Lounges', 'Co-working Areas', 'Premium Amenities'],
  },
  {
    id: 19,
    title: 'KM For Men PG',
    description: 'Comfortable PG accommodation with various room options and inclusive amenities',
    price: '₹5,000 - ₹8,000/month',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.2,
    location: 'Yeshwanthpur',
    type: 'Hostels',
    amenities: ['Free WiFi', 'Furnished Rooms', 'Water & Electricity Included', 'Security', 'Laundry'],
  },
  {
    id: 20,
    title: 'Lakshmi PG for Gents',
    description: 'Luxury PG with comprehensive meal options and modern amenities',
    price: '₹5,000/month',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    location: 'Bangalore',
    type: 'Hostels',
    amenities: ['Vegetarian & Non-vegetarian Meals', 'Breakfast, Lunch & Dinner', 'WiFi', 'Security', 'Laundry'],
  },
  {
    id: 21,
    title: 'BluO Park View 1BHK',
    description: 'A modern 1-bedroom apartment featuring a terrace garden, fully equipped kitchen, free Wi-Fi, air conditioning, and on-site parking. Ideal for short-term stays.',
    price: '₹4,500/night',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    location: 'HSR Layout, Bangalore',
    type: 'Homestays',
    amenities: ['Terrace Garden', 'Fully Equipped Kitchen', 'Free WiFi', 'Air Conditioning', 'On-site Parking', 'Modern Interiors'],
  },
  {
    id: 22,
    title: 'Sanctum Suites BEL Road',
    description: 'Serviced apartments offering free breakfast, Wi-Fi, air-conditioned rooms, and proximity to local attractions. Suitable for both business and leisure travelers.',
    price: '₹5,000/night',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    location: 'Armane Nagar, Bangalore',
    type: 'Homestays',
    amenities: ['Free Breakfast', 'WiFi', 'Air Conditioning', 'Business Center', 'Room Service', 'Local Attractions Nearby'],
  },
  {
    id: 23,
    title: 'Nandu Hospitality Apartments',
    description: 'Furnished apartments with amenities like free Wi-Fi, air conditioning, and on-site parking. Conveniently located near business districts.',
    price: '₹4,000/night',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    location: 'Nagavara, Bangalore',
    type: 'Homestays',
    amenities: ['Free WiFi', 'Air Conditioning', 'On-site Parking', 'Furnished Rooms', 'Business District Access', 'Kitchen'],
  },
  {
    id: 24,
    title: 'LUHO Grande',
    description: 'Luxury serviced apartments featuring modern interiors, fully equipped kitchens, free Wi-Fi, and close to shopping and dining options.',
    price: '₹6,000/night',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    location: 'Koramangala, Bangalore',
    type: 'Homestays',
    trending: true,
    amenities: ['Modern Interiors', 'Fully Equipped Kitchen', 'Free WiFi', 'Shopping Nearby', 'Dining Options', 'Luxury Amenities'],
  },
  {
    id: 25,
    title: 'Stayhome Suites',
    description: 'Fully furnished apartments with amenities such as free Wi-Fi, air conditioning, and kitchen facilities. Suitable for short-term rentals.',
    price: '₹3,500/night',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.2,
    location: 'Bilekahalli, Bangalore',
    type: 'Homestays',
    amenities: ['Free WiFi', 'Air Conditioning', 'Kitchen Facilities', 'Furnished Rooms', 'Short-term Rental', 'Parking'],
  },
  {
    id: 26,
    title: 'Eiffel Suites',
    description: 'Serviced apartments offering spacious rooms, free Wi-Fi, and kitchen facilities. Located in a vibrant neighborhood with easy access to local amenities.',
    price: '₹4,200/night',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    location: 'Kammanahalli, Bangalore',
    type: 'Homestays',
    amenities: ['Spacious Rooms', 'Free WiFi', 'Kitchen Facilities', 'Vibrant Neighborhood', 'Local Amenities', 'Parking'],
  },
  {
    id: 27,
    title: 'SPLENDID SHUBHAM SERVICED APARTMENTS',
    description: 'Modern serviced apartments equipped with free Wi-Fi, air conditioning, and kitchen facilities. Ideal for short stays.',
    price: '₹3,800/night',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.1,
    location: 'Bangalore',
    type: 'Homestays',
    amenities: ['Free WiFi', 'Air Conditioning', 'Kitchen Facilities', 'Modern Interiors', 'Short Stay Option', 'Parking'],
  },
  {
    id: 28,
    title: 'Ega Orchid Luxury Apartment',
    description: 'Luxury apartments offering free Wi-Fi, air conditioning, and fully equipped kitchens. Located near major IT parks.',
    price: '₹5,500/night',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    location: 'Brookefield, Bangalore',
    type: 'Homestays',
    trending: true,
    amenities: ['Free WiFi', 'Air Conditioning', 'Fully Equipped Kitchen', 'IT Park Proximity', 'Luxury Interiors', 'Parking'],
  },
  {
    id: 29,
    title: 'Palm Meadows Resort',
    description: 'Set amidst 5 acres of landscaped gardens, this resort offers a tranquil environment with luxurious facilities, making it ideal for both business and leisure travelers.',
    price: '₹7,000/night',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    location: 'Whitefield, Bangalore',
    type: 'Resorts',
    trending: true,
    amenities: ['Spacious Rooms', 'Multiple Swimming Pools', 'Spa Services', 'Fitness Center', 'On-site Dining', 'Landscaped Gardens'],
  },
  {
    id: 30,
    title: 'Clarks Exotica Convention Resort & Spa',
    description: 'Located near the airport, this resort is suitable for conferences, weddings, and relaxing getaways, offering a blend of luxury and convenience.',
    price: '₹6,500/night',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    location: 'Devanahalli Road, Bangalore',
    type: 'Resorts',
    trending: true,
    amenities: ['Well-appointed Rooms', 'Convention Facilities', 'Spa & Wellness Center', 'Outdoor Pool', 'Multiple Dining Venues'],
  },
  {
    id: 31,
    title: 'Wonderla Resort',
    description: 'Adjacent to the popular amusement park, this resort is perfect for families seeking fun-filled vacations with modern comforts.',
    price: '₹5,500/night',
    image: 'https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    location: 'Mysore Road, Bangalore',
    type: 'Resorts',
    amenities: ['Amusement Park Access', 'Swimming Pool', 'Fitness Center', 'In-house Restaurant', 'Family Activities'],
  },
  {
    id: 32,
    title: 'Royal Orchid Resort & Convention Centre',
    description: 'Set amidst 8 acres of greenery, this resort combines luxury with nature, making it ideal for events and leisurely stays.',
    price: '₹4,500/night',
    image: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    location: 'Yelahanka, Bangalore',
    type: 'Resorts',
    amenities: ['Elegant Rooms', 'Banquet Facilities', 'Outdoor Pool', 'Fitness Center', 'Multi-cuisine Restaurant'],
  },
  {
    id: 33,
    title: 'The Windflower Prakruthi Resort & Spa',
    description: 'Offering a mix of relaxation and adventure, this resort is set in a serene environment, perfect for weekend getaways.',
    price: '₹6,000/night',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    location: 'Devanahalli, Bangalore',
    type: 'Resorts',
    trending: true,
    amenities: ['Spacious Villas', 'Adventure Sports', 'Spa Services', 'Swimming Pool', 'Restaurant'],
  },
  {
    id: 34,
    title: 'Angsana Oasis Spa & Resort',
    description: 'This resort offers a rejuvenating experience with its extensive wellness facilities and lush surroundings.',
    price: '₹7,500/night',
    image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
    rating: 4.7,
    location: 'Doddaballapur Main Road, Bangalore',
    type: 'Resorts',
    trending: true,
    amenities: ['Luxurious Suites', 'Comprehensive Spa', 'Swimming Pool', 'Tennis Courts', 'Multiple Dining Options'],
  },
  {
    id: 35,
    title: 'Guhantara Resort',
    description: 'As India\'s first underground resort, Guhantara provides a unique experience blending adventure and relaxation.',
    price: '₹4,000/night',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    location: 'Kanakapura Road, Bangalore',
    type: 'Resorts',
    amenities: ['Cave-themed Rooms', 'Underground Pool', 'Adventure Activities', 'Spa', 'Restaurant'],
  },
  {
    id: 36,
    title: 'Our Native Village Eco Resort',
    description: 'This resort offers a rustic retreat, emphasizing sustainability and traditional village life experiences.',
    price: '₹5,000/night',
    image: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=800&q=80',
    rating: 4.4,
    location: 'Hesaraghatta, Bangalore',
    type: 'Resorts',
    amenities: ['Eco-friendly Accommodations', 'Organic Farming', 'Traditional Games', 'Swimming Pool', 'Local Cuisine'],
  },
  {
    id: 37,
    title: 'Signature Club Resort',
    description: 'Located near the airport, this resort is suitable for both business and leisure travelers, offering a range of recreational facilities.',
    price: '₹5,500/night',
    image: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?auto=format&fit=crop&w=800&q=80',
    rating: 4.3,
    location: 'Devanahalli, Bangalore',
    type: 'Resorts',
    amenities: ['Modern Rooms', 'Sports Facilities', 'Swimming Pool', 'Spa', 'Dining Options'],
  },
  {
    id: 38,
    title: 'Goldfinch Retreat',
    description: 'This resort offers a peaceful environment with modern amenities, making it ideal for transit stays and quick getaways.',
    price: '₹5,000/night',
    image: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80',
    rating: 4.2,
    location: 'Near Kempegowda International Airport, Bangalore',
    type: 'Resorts',
    amenities: ['Comfortable Rooms', 'Outdoor Pool', 'Fitness Center', 'Spa', 'Restaurant'],
  },
  {
    id: 39,
    title: '3 BHK Villa Whitefield',
    description: 'A spacious villa located in a prime area, suitable for families seeking comfortable living.',
    price: '₹90,000/month',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
    rating: 4.6,
    location: 'Whitefield, Bangalore',
    type: 'Resorts',
    trending: true,
    amenities: ['3 Bedrooms', '3 Bathrooms', 'Swimming Pool', 'Power Backup', 'Security', 'Parking'],
  },
  {
    id: 40,
    title: '3 BHK Villa Sarjapur Road',
    description: 'Luxury villa in a prime location with modern amenities and spacious living areas.',
    price: '₹85,000/month',
    image: 'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?auto=format&fit=crop&w=800&q=80',
    rating: 4.5,
    location: 'Sunny Brooks, Sarjapur Road, Bangalore',
    type: 'Resorts',
    trending: true,
    amenities: ['3 Bedrooms', 'Modern Kitchen', 'Garden', 'Security', 'Parking', 'Power Backup'],
  },
]; 